server:
  port: 8083
spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:mariadb://localhost:3306/warehousedb
    username: root
    password: gavallo97
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      default-zone: http://eurekadiscovery:8761/eureka

