DROP DATABASE IF EXISTS orders;
CREATE DATABASE orders;
DROP DATABASE IF EXISTS wallet;
CREATE DATABASE wallet;
DROP DATABASE IF EXISTS warehouse;
CREATE DATABASE warehouse;
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'admin';
