DROP DATABASE IF EXISTS catalogdb;
CREATE DATABASE catalogdb;
DROP DATABASE IF EXISTS orderdb;
CREATE DATABASE  orderdb;
DROP DATABASE IF EXISTS walletdb;
CREATE DATABASE walletdb;
DROP DATABASE IF EXISTS warehousedb;
CREATE DATABASE warehousedb;
